packages:
  - packages/*
  - sandbox/*
catalog:
  '@total-typescript/ts-reset': ^0.6.1
  '@total-typescript/tsconfig': ^1.0.4
  '@vitest/coverage-v8': ^2.0.5
  nuxt: ^3.13.1
  tsup: ^8.2.4
  tsx: ^4.19.0
  typescript: ^5.5.4
  vitest: ^2.0.5
  vue: ^3.5.2
  vue-tsc: ^2.1.6
