name: Continuous integration

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.event.pull_request.number || github.ref }}

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  lint:
    runs-on: ubuntu-latest

    environment: Testing

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-cache

      - name: Install dependencies
        run: pnpm install

      - name: Lint code with ESLint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest

    environment: Testing

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-cache

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

  test:
    runs-on: ubuntu-latest

    environment: Testing

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-cache

      - name: Install dependencies
        run: pnpm install

      - name: Test
        if: github.event_name == 'push'
        run: pnpm run test --coverage
